# Generated by Django 5.2.7 on 2025-10-16 05:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Balance',
                'verbose_name_plural': 'Account Balances',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('timestamp', models.DateTimeField(help_text='When the trade was taken')),
                ('symbol', models.CharField(choices=[('NQ', 'NQ - Nasdaq'), ('ES', 'ES - S&P 500'), ('YM', 'YM - Dow Jones'), ('RTY', 'RTY - Russell 2000'), ('EURUSD', 'EUR/USD'), ('GBPUSD', 'GBP/USD'), ('USDJPY', 'USD/JPY'), ('USDCHF', 'USD/CHF'), ('AUDUSD', 'AUD/USD'), ('NZDUSD', 'NZD/USD'), ('USDCAD', 'USD/CAD'), ('XAUUSD', 'XAU/USD (Gold)'), ('XAGUSD', 'XAG/USD (Silver)')], max_length=10)),
                ('direction', models.CharField(choices=[('LONG', 'Long'), ('SHORT', 'Short')], max_length=10)),
                ('entry_type', models.CharField(choices=[('CONFIRMATION', 'Confirmation'), ('FAIL_FLIP', 'Fail Flip')], max_length=20)),
                ('timeframe_analysis', models.CharField(default='1D → 1H → 5M', help_text='Timeframe analysis used', max_length=50)),
                ('entry_price', models.DecimalField(decimal_places=5, help_text='Entry price', max_digits=12)),
                ('stop_loss', models.DecimalField(decimal_places=5, help_text='Stop loss price', max_digits=12)),
                ('take_profit', models.DecimalField(decimal_places=5, help_text='Take profit price', max_digits=12)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, help_text='Exit price', max_digits=12, null=True)),
                ('lot_size', models.DecimalField(decimal_places=2, help_text='Position size in lots (e.g., 0.01, 1.0)', max_digits=5)),
                ('capital', models.DecimalField(decimal_places=2, help_text='Account capital/balance at time of trade (USD)', max_digits=12)),
                ('confidence_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('outcome', models.CharField(choices=[('WINNER', 'Winner'), ('LOSER', 'Loser'), ('SCRATCH', 'Scratch'), ('OPEN', 'Open')], default='OPEN', max_length=10)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='P&L in USD', max_digits=10)),
                ('risk_pips', models.DecimalField(decimal_places=1, default=0, editable=False, help_text='Risk in pips', max_digits=10)),
                ('reward_pips', models.DecimalField(decimal_places=1, default=0, editable=False, help_text='Reward in pips', max_digits=10)),
                ('pnl_pips', models.DecimalField(decimal_places=1, default=0, editable=False, help_text='P&L in pips', max_digits=10)),
                ('risk_reward_ratio', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('screenshot', models.ImageField(blank=True, help_text='Optional screenshot of the trade setup', null=True, upload_to='trade_screenshots/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the trade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'ordering': ['-timestamp'],
            },
        ),
    ]
